# Actions for Home Arrival
- id: auto1
  alias: Actions When Arriving Home
  initial_state: true
  hide_entity: false
  trigger:
  - entity_id: sensor.anyone_home
    from: 'False'
    platform: state
    to: 'True'
  action:
    - service: switch.turn_off
      entity_id: switch.yi_camera_smart_plug
    - service: automation.turn_on
      entity_id: automation.auto41
    - service: switch.turn_on
      entity_id: switch.christmas_tree

# Actions for home exit
- id: auto2
  alias: Actions When Leaving Home
  initial_state: true
  hide_entity: false
  trigger:
  - entity_id: sensor.anyone_home
    from: 'True'
    platform: state
    to: 'False'
  action:
    - service: switch.turn_on
      entity_id: switch.yi_camera_smart_plug
    - service: automation.turn_off
      entity_id: automation.auto41
    - service: switch.turn_off
      entity_id: switch.christmas_tree

# Hallway sensor intruder alert
- id: auto3
  alias: Intruder Alert Hallway
  initial_state: true
  hide_entity: false
  trigger:
  - entity_id: sensor.hallway_motion
    from: '0'
    platform: state
    to: '1'
  - entity_id: sensor.hallway_motion
    from: '0'
    platform: state
    to: '2'
  condition: 
    condition: state
    entity_id: sensor.anyone_home
    state: 'False'
  action:
    service: notify.my_pushbullet
    data_template:
      title: "Intruder Alert: Hallway"
      message: "Detected motion in the upstairs hallway."

# Garage sensor intruder alert
- id: auto4
  alias: Intruder Alert Garage
  initial_state: true
  hide_entity: false
  trigger:
  - entity_id: sensor.garage_motion
    from: '0'
    platform: state
    to: '1'
  - entity_id: sensor.garage_motion
    from: '0'
    platform: state
    to: '2'
  condition: 
    condition: state
    entity_id: sensor.anyone_home
    state: 'False'
  action:
    service: notify.my_pushbullet
    data_template:
      title: "Intruder Alert: Garage"
      message: "Detected motion in the garage."

# Garage sensor intruder alert
- id: auto41
  alias: Motion Alert Garage
  initial_state: true
  hide_entity: false
  trigger:
  - entity_id: sensor.garage_motion
    from: '0'
    platform: state
    to: '1'
  - entity_id: sensor.garage_motion
    from: '0'
    platform: state
    to: '2'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '01:00:00'
      - condition: time
        before: '07:00:00'
  action:
    service: notify.my_pushbullet
    data_template:
      title: "Activity Alert: Garage"
      message: "Detected motion in the garage."
      
# Patio sensor intruder alert
- id: auto5
  alias: Intruder Alert Patio
  initial_state: true
  hide_entity: false
  trigger:
  - entity_id: sensor.patio_motion
    from: '0'
    platform: state
    to: '1'
  - entity_id: sensor.patio_motion
    from: '0'
    platform: state
    to: '2'
  condition: 
    condition: state
    entity_id: sensor.anyone_home
    state: 'False'
  action:
    service: notify.my_pushbullet
    data_template:
      title: "Intruder Alert: Patio"
      message: "Detected motion on the patio."

# Hallway sensor intruder alert
- id: auto6
  alias: Motion Alert Hallway at Night
  initial_state: true
  hide_entity: false
  trigger:
  - entity_id: sensor.hallway_motion
    from: '0'
    platform: state
    to: '1'
  - entity_id: sensor.hallway_motion
    from: '0'
    platform: state
    to: '2'
  condition:
    condition: or
    conditions:
      - condition: time
        after: '20:00:00'
      - condition: time
        before: '07:00:00'
  action:
    service: notify.tv
    data:
      message: "Motion alert for upstairs hallway!"

# Hue Motion Sensor Light Level Update to Flux
- id: flux_lightlevel
  alias: Flux Lightlevel
  initial_state: true
  hide_entity: false
  trigger:
  - entity_id: sensor.outside_lightlevel
    platform: state
  action:
    - service: rest_command.flux_lightlevel_set

#  condition: 
#    condition: state
#    entity_id: sensor.daylight
#    state: 'true'
    
 # Bose Presets
#- id: auto7
#  alias: Bose Presets
#  trigger:
#  - platform: state
#    entity_id: input_number.theater, input_number.kitchen
#  action:
#  - service: media_player.play_media
#    data_template:
#      entity_id: >
#        {% if trigger.entity_id == "input_number.theater" %} media_player.theater
#        {% else %} media_player.kitchen {% endif %}
#      media_content_id: '{{ trigger.to_state.state | int }}'
#      media_content_type: 'music'
#  - service: media_player.volume_set
#    data:
#      entity_id: media_player.theater, media_player.kitchen
#      volume_level: 0.2
#  - service: media_player.soundtouch_play_everywhere
#    data:
#      master: media_player.kitchen

- id: pc_speaker_keep_alive
  alias: "PC Set Source"
  initial_state: true
  trigger:
    - entity_id: media_player.pc
      platform: state
      to: 'off'
  action:
    - service: rest_command.pc_source_select_aux
      
- id: update_friendly_names
  alias: "Set Forecast Day Names"
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - sensor.forecast_1
        - sensor.forecast_2
        - sensor.forecast_3
        - sensor.forecast_4
        - sensor.forecast_5
        - sensor.forecast_6
    - platform: homeassistant
      event: start
  action:
    - service: python_script.dark_sky_friendly_names
      data_template:
        entityid: '{{trigger.entity_id}}'
          
#            {% if is_state("input_text.rfid_uid", "74920810") %} script.toggle_play_everywhere

# RFID Reader Duplicate Trigger Script
- id: auto9
  alias: RFID Duplicate Interpreter
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.rfid_uid
  condition: 
  - condition: template
    value_template: >
      {% if is_state("input_text.rfid_uid", "None") %} false
      {% elif is_state("input_text.rfid_uid_last", "None") %} false
      {% elif states("input_text.rfid_uid") == states("input_text.rfid_uid_last") %} true
      {% else %} false {% endif %}
  action:
  - service: input_text.set_value
    data:
      entity_id: input_text.rfid_uid
      value: None      
  - service: media_player.media_next_track
    entity_id: media_player.spotify

# RFID Reader Trigger Script
- id: auto8
  alias: RFID Interpreter
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.rfid_uid
  condition: 
  - condition: template
    value_template: >
      {% if is_state("input_text.rfid_uid", "None") %} false
      {% elif states("input_text.rfid_uid") == states("input_text.rfid_uid_last") %} false
      {% else %} true {% endif %}
  action:
  - service: script.turn_on
    entity_id: script.spotify_select_source
  - delay: '00:00:01'
  - service: script.turn_on
    data_template:
      entity_id: >
        {% if is_state("input_text.rfid_uid", "74862954") %} script.play_illenium
        {% elif is_state("input_text.rfid_uid", "80572266") %} script.play_hawaiian_reggae
        {% elif is_state("input_text.rfid_uid", "68396906") %} script.play_chris_issak
        {% elif is_state("input_text.rfid_uid", "72695658") %} script.play_seven_lions
        {% elif is_state("input_text.rfid_uid", "69164394") %} script.play_meghan_trainor
        {% elif is_state("input_text.rfid_uid", "73226346") %} script.play_deep_focus
        {% elif is_state("input_text.rfid_uid", "79371370") %} script.play_country_icon
        {% elif is_state("input_text.rfid_uid", "71271274") %} script.play_josh_turner
        {% elif is_state("input_text.rfid_uid", "81564778") %} script.play_jo_jo_siwa
        {% elif is_state("input_text.rfid_uid", "77112170") %} script.play_jack_johnson
        {% endif %}
  - service: script.turn_on
    entity_id: script.kitchen_volume_set
  - service: input_text.set_value
    data_template:
      entity_id: input_text.rfid_uid_last
      value: "{{ states('input_text.rfid_uid') }}"
  - service: input_text.set_value
    data:
      entity_id: input_text.rfid_uid
      value: None
  - delay: '00:00:01'
  - service: script.turn_on
    entity_id: script.spotify_shuffle_set
  - service: script.turn_on
    entity_id: script.play_everywhere
#  - service: script.turn_on
#    entity_id: script.kitchen_turn_on
#  - service: script.turn_on
#    entity_id: script.kitchen_media_play
      
- id: auto10
  alias: Reset Duplicate ID on Stop Playing
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.kitchen
  condition: 
  - condition: state
    entity_id: media_player.kitchen
    state: 'off'
  action:
  - service: input_text.set_value
    data:
      entity_id: input_text.rfid_uid_last
      value: None

# Garage Door Button
- id: auto88
  alias: Garage Button Pressed
  initial_state: true
  hide_entity: false
  trigger:
  - entity_id: sensor.garage_button
    platform: state
  action:
    - service: script.turn_on
      entity_id: script.garage_button 

#- id: auto98
#  alias: Turn On  Christmas Tree
#  description: ''
#  trigger:
#  - entity_id: sensor.switch_downstairs
#    platform: state
#    to: '1_click_up'
#  condition: []
#  action:
#  - service: switch.turn_on
#    entity_id: switch.christmas_tree

#- id: auto99
#  alias: Turn Off Christmas Tree
#  description: ''
#  trigger:
#  - entity_id: sensor.switch_downstairs
#    platform: state
#    to: '4_click_up'
#  condition: []
#  action:
#  - service: switch.turn_off
#    entity_id: switch.christmas_tree