
  - platform: group
    name: Bedroom Blinds
    entities:
      - cover.james_blind_1
      - cover.james_blind_2
      - cover.nathan_blind
      
  - platform: group
    name: James' Blinds
    entities:
      - cover.james_blind_1
      - cover.james_blind_2
  
  - platform: group
    name: Downstairs Blinds
    entities:
      - cover.kitchen_nook_blind_east
      - cover.kitchen_nook_blind_west

  - platform: group
    name: All Blinds
    entities:
      - cover.james_blind_1
      - cover.james_blind_2
      - cover.nathan_blind
      - cover.kitchen_nook_blind_east
      - cover.kitchen_nook_blind_west
