group.all_automations:
  hidden: false
group.all_scripts:
  hidden: false
group.all_lights:
  hidden: true
  
# Presence Profile Photos
sensor.wife_home:
  entity_picture: /local/victoria.jpg
  friendly_name: Victoria
sensor.me_home:
  entity_picture: /local/profile.jpg
  friendly_name: Sleezly

# Flux
sensor.flux:
  friendly_name: Flux Temperature
sensor.flux_on:
  hidden: true
switch.flux:
  friendly_name: Flux Service
#  icon_template: {% if is_state("

# Nest
climate.hallway_nest:
  friendly_name: Nest

# Dark Sky
automation.update_friendly_names:
  hidden: false
sensor.season:
  hidden: true
sensor.weekday:
  hidden: true
sensor.dark_sky_daily_summary:
  friendly_name: Daily Summary
  hidden: false
sensor.dark_sky_summary:
  hidden: true
sensor.dark_sky_temperature:
  friendly_name: Temperature
  hidden: false
sensor.dark_sky_daily_high_temperature:
  hidden: true
sensor.dark_sky_daily_high_temperature_1:
  hidden: true
sensor.dark_sky_daily_high_temperature_2:
  hidden: true
sensor.dark_sky_daily_high_temperature_3:
  hidden: true
sensor.dark_sky_daily_high_temperature_4:
  hidden: true
sensor.dark_sky_daily_high_temperature_5:
  hidden: true
sensor.dark_sky_daily_high_temperature_6:
  hidden: true
sensor.dark_sky_daily_high_temperature_7:
  hidden: true
sensor.dark_sky_daily_low_temperature:
  hidden: true
sensor.dark_sky_daily_low_temperature_1:
  hidden: true
sensor.dark_sky_daily_low_temperature_2:
  hidden: true
sensor.dark_sky_daily_low_temperature_3:
  hidden: true
sensor.dark_sky_daily_low_temperature_4:
  hidden: true
sensor.dark_sky_daily_low_temperature_5:
  hidden: true
sensor.dark_sky_daily_low_temperature_6:
  hidden: true
sensor.dark_sky_daily_low_temperature_7:
  hidden: true
sensor.dark_sky_humidity:
  friendly_name: Humidity
  hidden: false
sensor.dark_sky_humidity_1:
  hidden: true
sensor.dark_sky_humidity_2:
  hidden: true
sensor.dark_sky_humidity_3:
  hidden: true
sensor.dark_sky_humidity_4:
  hidden: true
sensor.dark_sky_humidity_5:
  hidden: true
sensor.dark_sky_humidity_6:
  hidden: true
sensor.dark_sky_humidity_7:
  hidden: true
sensor.dark_sky_icon:
  hidden: true
sensor.dark_sky_icon_1:
  hidden: true
sensor.dark_sky_icon_2:
  hidden: true
sensor.dark_sky_icon_3:
  hidden: true
sensor.dark_sky_icon_4:
  hidden: true
sensor.dark_sky_icon_5:
  hidden: true
sensor.dark_sky_icon_6:
  hidden: true
sensor.dark_sky_icon_7:
  hidden: true
sensor.dark_sky_precip_probability:
  hidden: true
sensor.dark_sky_precip_probability_1:
  hidden: true
sensor.dark_sky_precip_probability_2:
  hidden: true
sensor.dark_sky_precip_probability_3:
  hidden: true
sensor.dark_sky_precip_probability_4:
  hidden: true
sensor.dark_sky_precip_probability_5:
  hidden: true
sensor.dark_sky_precip_probability_6:
  hidden: true
sensor.dark_sky_precip_probability_7:
  hidden: true
  
# Nest
binary_sensor.hallway_thermostat_nest_fan:
  hidden: true
binary_sensor.hallway_thermostat_nest_has_leaf:
  hidden: true
binary_sensor.hallway_thermostat_nest_is_using_emergency_heat:
  hidden: true
binary_sensor.hallway_thermostat_nest_online:
  hidden: true
binary_sensor.hallway_thermostat_nest_is_locked:
  hidden: true
sensor.hallway_thermostat_nest_operation_mode:
  hidden: true
sensor.hallway_thermostat_nest_humidity:
  hidden: true
sensor.hallway_thermostat_nest_temperature:
  hidden: true
sensor.hallway_thermostat_nest_target:
  friendly_name: Nest Target
sensor.hallway_thermostat_nest_hvac_state:
  friendly_name: Nest State

