climate.hallway_nest:
  name:
  platform: nest
  unique_id: n7_mMb_W-FgFBStyrnlHCaKsDb_6jV7s
light.inside_garage_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:52:12:71-0b
light.outside_downlight_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:76:33:0f-0b
light.outside_downlight_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:76:57:49-0b
light.inside_garage_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:43:11:18-0b
light.backyard_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:52:1c:0f-0b
light.backyard_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:52:1c:0e-0b
light.outside_garage_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:43:82:fd-0b
light.outside_garage_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:52:d5:41-0b
light.bedroom_james_ceiling_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:34:72:b4-0b
light.bedroom_hall_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:76:32:60-0b
light.kitchen_ceiling_4:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:76:3e:b7-0b
light.kitchen_ceiling_3:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:76:32:51-0b
light.kitchen_ceiling_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:76:2b:47-0b
light.kitchen_ceiling_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:76:2c:b2-0b
light.mantle:
  name:
  platform: hue
  unique_id: 00:17:88:01:01:1e:d7:4c-0b
light.theater_lamp_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:76:d4:97-0b
light.bedroom_james_lamp:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:71:a1:cd-0b
light.bedroom_anna_lamp:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:73:a7:eb-0b
light.formal_dining_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:32:7d:39-0b
light.formal_dining_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:35:6a:80-0b
light.bedroom_master_lamp:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:73:ac:01-0b
light.bedroom_anna_closet:
  name:
  platform: hue
  unique_id: 00:17:88:01:03:5b:74:b9-0b
light.washroom_downlight_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:03:78:82:76-0b
light.tv:
  name:
  platform: hue
  unique_id: 00:17:88:01:01:1f:08:c3-0b
light.dining_table:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:72:b4:31-0b
light.bedroom_master_lightstrip:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:17:5d:0e-0b
light.bedroom_nathan_lamp:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:70:8f:b5-0b
light.washroom_downlight_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:03:51:0f:b1-0b
light.formal_dining_3:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:34:a8:69-0b
light.kitchen_sink:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:7d:14:ab-0b
light.kitchen_strip_dishwasher:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:17:4c:f4-0b
light.kitchen_strip_coffee:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:ad:c9:2a-0b
light.bedroom_james_ceiling_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:32:ae:16-0b
light.bedroom_hall_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:ab:34:82-0b
light.bedroom_anna_ceiling_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:32:aa:c2-0b
light.kitchen_strip_oven:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:ad:dd:2d-0b
light.theater_lamp_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:70:89:ee-0b
light.bedroom_anna_ceiling_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:34:79:c4-0b
light.kitchen_strip_microwave:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:ad:d5:da-0b
light.bedroom_hall_3:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:a9:10:16-0b
light.office_3:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:34:99:44-0b
light.bedroom_nathan_ceiling_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:32:a7:69-0b
light.entry_3:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:56:bd:2b-0b
light.bedroom_nathan_ceiling_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:32:ad:70-0b
light.entry_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:94:4b:4f-0b
light.bedroom_master_ceiling_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:32:59:3b-0b
light.entry_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:24:e0:60-0b
light.go:
  name:
  platform: hue
  unique_id: 00:17:88:01:01:14:e6:7d-0b
light.bedroom_master_ceiling_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:32:74:28-0b
light.office_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:33:71:5e-0b
light.office_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:02:34:73:53-0b
light.laundry_1:
  name:
  platform: hue
  unique_id: 00:17:88:01:03:57:1c:c6-0b
light.laundry_2:
  name:
  platform: hue
  unique_id: 00:17:88:01:03:5b:5e:42-0b
light.bedroom_master_closet:
  name:
  platform: hue
  unique_id: 00:17:88:01:03:57:1c:c9-0b
sensor.iphone_battery_state:
  name:
  platform: ios
  unique_id: state_iphone
sensor.iphone_battery_level:
  name:
  platform: ios
  unique_id: level_iphone
