  default_view:
    name: Home Sweet Home
    icon: mdi:home
    entities:
      - sensor.date_time
      - sensor.forecast_today
      - sensor.forecast_1
      - sensor.forecast_2
      - sensor.forecast_3
      - sensor.forecast_4
      - sensor.forecast_5
      - sensor.forecast_6
      - sensor.temperature
      - sensor.forecast_summary
      - climate.hallway_nest
      - script.hue_relax
      - script.hue_dinner
      - script.hue_tv

  media_view:
    name: Media
    icon: mdi:play
    entities:
      - script.play_everywhere_always
      - script.play_everywhere_pc
      - script.pair_pc_to_kitchen
      - media_player.spotify
      - media_player.kitchen
      - media_player.theater
      - media_player.pc
#      - media_player.tv

  downstairs_lights_view:
    name: Lights
    icon: mdi:lightbulb-on
    entities:
      - light.downstairs
      - light.accent_lights
      - light.theater_lights
      - light.kitchen_lights
      - light.dining_lights
      - light.office_lights
      - light.entry_lights
      - light.bedroom_hallway
      - light.master_lights
      - light.bedroom_anna
      - light.bedroom_james
      - light.bedroom_nathan
      - light.bathroom
      - light.outside_lights

  flux_view:
    name: Flux
    icon: mdi:home-automation
    entities:
      - sensor.outside_temp
      - sensor.hallway_temp
      - sensor.outside_lightlevel
      - sensor.flux_temperature
      - sensor.flux_brightness
      - switch.flux

  seensors_view:
    name: Sensors
    icon: mdi:shield-home
    entities:
      - script.garage_opener
      - sensor.garage_door
      - sensor.pantry_door
      - sensor.anyone_home
      - sensor.wife_home
      - sensor.me_home
      - switch.guest
      - cover.all_blinds
      - cover.downstairs_blinds
      - cover.kitchen_nook_blind_east
      - cover.kitchen_nook_blind_west
      - cover.james_blinds
      - cover.blind_nathan
      - switch.yi_home_outlet
      - switch.christmas_tree
      - switch.annas_nightlight
      - switch.door_alarms
      - switch.adguard

  music_view:
    name: Music
    icon: mdi:music
    entities:
      - script.play_meghan_trainor
      - script.play_chris_issak
      - script.play_seven_lions
      - script.play_hawaiian_reggae
      - script.play_illenium
      - script.play_deep_focus
      - script.play_country_icon
      - script.play_josh_turner
      - script.play_jack_johnson
      - script.play_jo_jo_siwa

#  rfid_view:
#    name: RFID
#    icon: mdi:nfc-tap
#    entities:
#      - input_text.rfid_uid
#      - input_text.rfid_uid_last
#      - media_player.spotify
#      - media_player.kitchen
#      - media_player.theater
#      - media_player.tv

#  scripts_view:
#    name: All Scripts
#    icon: mdi:flash
#    entities:
#      - group.all_scripts
      
#  automations_view:
#    name: All Automations
#    icon: mdi:flash-auto
#    entities: 
#      - group.all_automations

  settings:
    name: Settings
    icon: mdi:settings
    entities:
      - script.home_assistant_restart
      - script.pc_audio_to_aux
      - script.execute_fix_soundbar
