  default_view:
    view: yes
    name: Home Sweet Home
    icon: mdi:home
    entities:
      - group.weather_card_forecast
      - climate.hallway_nest
      - group.scene_card
      
  media_view:
    name: Media
    view: yes
    icon: mdi:play
    entities:
      - light.media_lights
      - script.play_everywhere_always
      - media_player.spotify
      - media_player.kitchen
      - media_player.theater
      - media_player.pc
      - weblink.photos
#      - media_player.tv

  downstairs_lights_view:
    name: Downstairs Lights
    view: yes
    icon: mdi:lightbulb-on
    entities:
      - light.downstairs_lights
      - light.accent_lights
      - light.theater_lights
      - light.kitchen_lights
      - light.dining_lights
      - light.office_lights
      - light.entry_lights
      
  music_view:
    name: Music
    view: yes
    icon: mdi:music-box
    entities:
      - script.play_meghan_trainor
      - script.play_chris_issak
      - script.play_seven_lions
      - script.play_hawaiian_reggae
      - script.play_illenium
      - script.play_deep_focus
      - script.play_country_icon
      - script.play_josh_turner
      - script.play_jack_johnson
      - script.play_jo_jo_siwa
      
  bedroom_lights_view:
    name: Bedroom Lights
    view: yes
    icon: mdi:bed-empty
    entities:
      - light.bedroom_hallway
      - light.master_lights
      - light.bedroom_anna
      - light.bedroom_james
      - light.bedroom_nathan
  
  sensors_view:
    view: yes
    name: Sensors
    icon: mdi:home-automation
    entities:
      - sensor.outside_temp
      - sensor.hallway_temp
      - sensor.outside_lightlevel
      - sensor.flux
      - sensor.flux_brightness
      - switch.flux
      - sensor.garage_motion
      - sensor.hallway_motion
      - sensor.patio_motion
#      - sensor.daylight
      
  security_view:
    view: yes
    name: Security
    icon: mdi:security-home
    entities:
      - sensor.anyone_home
      - sensor.wife_home
      - sensor.me_home
      - switch.guest
      - switch.yi_home_camera_smart_plug
      - light.outside_lights

  rfid_view:
    view: yes
    name: RFID
    icon: mdi:nfc-tap
    entities:
      - input_text.rfid_uid
      - input_text.rfid_uid_last
      - media_player.spotify
      - media_player.kitchen
      - media_player.theater
      - media_player.tv

  scripts_view:
    view: yes
    name: All Scripts
    icon: mdi:flash
    control: hidden
    entities:
      - group.all_scripts
      
  automations_view:
    view: yes
    name: All Automations
    icon: mdi:flash-auto
    control: hidden
    entities: 
      - group.all_automations

  weather_card_forecast:
    name: Weekly Forecast
    view: no
    entities:
      - sensor.date__time
      - sensor.forecast_today
      - sensor.forecast_1
      - sensor.forecast_2
      - sensor.forecast_3
      - sensor.forecast_4
      - sensor.forecast_5
      - sensor.forecast_6
      - sensor.temperature
      - sensor.forecast_summary
  
  scene_card:
    name: Scenes
    view: no
    control: hidden
    entities:
      - script.hue_relax
      - script.hue_dinner
      - script.hue_tv
  
