  - platform: group
    name: Accent Lights
    entities:
      - light.tv_accent_bias
      - light.tv_accent_mantle
      - light.kitchen_accent_coffee
      - light.kitchen_accent_dishwasher
      - light.kitchen_accent_microwave
      - light.kitchen_accent_oven

  - platform: group
    name: Theater Lights
    entities:
      - light.theater_lamp_1
      - light.theater_lamp_2
      - light.tv_accent_bias
      - light.tv_accent_mantle
      - light.mantle_ceiling_1
      - light.mantle_ceiling_2
      - light.mantle_ceiling_3

  - platform: group
    name: Dining Lights
    entities:
      - light.dining_1
      - light.dining_2
      - light.dining_3

  - platform: group
    name: Office Lights
    entities:
      - light.office_1
      - light.office_2
      - light.office_3
      - light.formal_dining_1
      - light.formal_dining_2
      - light.formal_dining_3

  - platform: group
    name: Kitchen Lightstrips
    entities:
      - light.kitchen_accent_coffee
      - light.kitchen_accent_dishwasher
      - light.kitchen_accent_microwave
      - light.kitchen_accent_oven
      
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_sink
      - light.kitchen_ceiling_1
      - light.kitchen_ceiling_2
      - light.kitchen_ceiling_3
      - light.kitchen_ceiling_4
      - light.kitchen_accent_coffee
      - light.kitchen_accent_dishwasher
      - light.kitchen_accent_microwave
      - light.kitchen_accent_oven

  - platform: group
    name: Entry Lights
    entities:
      - light.entry_1
      - light.entry_2
      - light.entry_3

  - platform: group
    name: Downstairs Lights
    entities:
      - light.theater_lamp_1
      - light.theater_lamp_2
      - light.tv_accent_bias
      - light.tv_accent_mantle
      - light.entry_1
      - light.entry_2
      - light.entry_3
      - light.kitchen_sink
      - light.kitchen_ceiling_1
      - light.kitchen_ceiling_2
      - light.kitchen_ceiling_3
      - light.kitchen_ceiling_4
      - light.kitchen_accent_coffee
      - light.kitchen_accent_dishwasher
      - light.kitchen_accent_microwave
      - light.kitchen_accent_oven
      - light.office_1
      - light.office_2
      - light.office_3
      - light.formal_dining_1
      - light.formal_dining_2
      - light.formal_dining_3
      - light.dining_1     
      - light.dining_2
      - light.dining_3
      - light.mantle_ceiling_1
      - light.mantle_ceiling_2
      - light.mantle_ceiling_3
      
  - platform: group
    name: Bedroom Hallway
    entities:
      - light.bedroom_hall_1
      - light.bedroom_hall_2
      - light.bedroom_hall_3

  - platform: group
    name: Master Lights
    entities:
      - light.master_ceiling_1
      - light.master_ceiling_2
      - light.bedroom_master_closet
      - light.master_bedside_lamp
      - light.master_accent_headboard
      - light.master_accent_go

  - platform: group
    name: Bedroom Anna
    entities:
      - light.bedroom_anna_ceiling_1
      - light.bedroom_anna_ceiling_2
      - light.bedroom_anna_closet
      - light.bedroom_anna_lamp

  - platform: group
    name: Bedroom James
    entities:
      - light.bedroom_james_ceiling_1
      - light.bedroom_james_ceiling_2
      - light.bedroom_james_lamp

  - platform: group
    name: Bedroom Nathan
    entities:
      - light.bedroom_nathan_ceiling_1
      - light.bedroom_nathan_ceiling_2
      - light.bedroom_nathan_lamp

  - platform: group
    name: Bathroom
    entities:
    - light.bathroom_1
    - light.bathroom_2
    - light.bathroom_3

  - platform: group
    name: Laundry
    entities:
      - light.laundry_2

  - platform: group
    name: Garage
    entities:
      - light.inside_garage_1
      - light.inside_garage_2

  - platform: group
    name: Outside Lights
    entities:
      - light.outside_front_1
      - light.outside_front_2
      - light.outside_front_3
      - light.outside_front_4

  - platform: group
    name: Outside Backyard
    entities:
      - light.backyard_1
      - light.backyard_2

