#tv_time:
#  alias: 'office light script'
#  sequence:
#    service: light.toggle
#    data:
#        entity_id: light.office_1
        
#home_leave:
#  alias: 'Leave Home Script'
#  sequence:
#    service: hue.hue_activate_scene
#    data:
#      group_name: Downstairs
#      scene_name: Relax

#play_preset_1:
#   alias: 'Play Bose Preset 1'
#   sequence:
#     service: media_player.play_media
#     data:
#       entity_id: media_player.kitchen
#       media_content_id: '1'
#       media_content_type: 'music'


# Hue Scenes
hue_dinner:
  alias: "Dinner Lights"
  sequence:
  - service: rest_command.hue_scene_dinner_downstairs
  - service: rest_command.hue_scene_dinner_accents
  - service: rest_command.hue_scene_tv_entry

hue_relax:
  alias: "Full Lights"
  sequence:
  - service: rest_command.hue_scene_flux_downstairs
  - service: rest_command.hue_scene_flux_accents
  - service: rest_command.hue_scene_flux_entry
      
hue_tv:
  alias: "TV Lights"
  sequence:
  - service: rest_command.hue_scene_tv_downstairs
  - service: rest_command.hue_scene_tv_accents
  - service: rest_command.hue_scene_tv_entry
      
hue_midnight:
  alias: "Night Lights"
  sequence:
  - service: hue.hue_activate_scene
    data:
      group_name: Downstairs
      scene_name: Midnight

play_meghan_trainor:
  alias: 'Play Meghan Trainor'
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify
      media_content_id: 'spotify:artist:6JL8zeS1NmiOftqZTRgdTz'
      media_content_type: 'playlist'

play_chris_issak:
  alias: 'Play Chris Issak'
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify
      media_content_id: 'spotify:artist:7290H8m1Dwt8G7jm1y9CQx'
      media_content_type: 'playlist'

play_seven_lions:
  alias: 'Play Seven Lions'
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify
      media_content_id: 'spotify:artist:6fcTRFpz0yH79qSKfof7lp'
      media_content_type: 'playlist'

play_hawaiian_reggae:
  alias: 'Play Hawaiian Reggae'
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify
      media_content_id: 'spotify:user:1214764388:playlist:588rONRknunC0Slquv8jps'
      media_content_type: 'playlist'
      
play_illenium:
  alias: 'Play Illenium'
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify
      media_content_id: 'spotify:artist:45eNHdiiabvmbp4erw26rg'
      media_content_type: 'playlist'

play_deep_focus:
  alias: 'Play Deep Focus'
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify
      media_content_id: 'spotify:user:spotify:playlist:37i9dQZF1DWZeKCadgRdKQ'
      media_content_type: 'playlist'

play_country_icon:
  alias: 'Play Country Icon'
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify
      media_content_id: 'spotify:user:spotify:playlist:37i9dQZF1DWVpjAJGB70vU'
      media_content_type: 'playlist'

play_josh_turner:
  alias: 'Play Josh Turner'
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify
      media_content_id: 'spotify:artist:7vCtweS8UVAXTyau2j0rDT'
      media_content_type: 'playlist'

play_jo_jo_siwa:
  alias: 'Play Jo Jo Siwa'
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify
      media_content_id: 'spotify:user:tomasete06:playlist:40k6jTpOfkSQjPWvWMieJI'
      media_content_type: 'playlist'

play_jack_johnson:
  alias: 'Play Jack Johnson'
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify
      media_content_id: 'spotify:artist:3GBPw9NK25X1Wt2OUvOwY3'
      media_content_type: 'playlist'
      
# Turns on the Kitchen player if it's currently off
kitchen_turn_on:
  alias: Turn On Kitchen
  sequence:
  - condition: template
    value_template: >
      {% if is_state("media_player.kitchen", "off") %} true
      {% else %} false {% endif %}
  - service: media_player.turn_on
    entity_id: media_player.kitchen

# Kitchen Volume
kitchen_volume_set:
  alias: Set Kitchen Volume
  sequence:
  - service: media_player.volume_set
    data:
      entity_id: media_player.kitchen
      volume_level: 0.35
      
# Starts kitchen playback
kitchen_media_play:
  alias: Play Kitchen
  sequence:
  - condition: template
    value_template: >
      {% if is_state("media_player.kitchen", "playing") %} false
      {% else %} true {% endif %}
  - service: media_player.media_play
    entity_id: media_player.kitchen

# Sets the Spotify shuffle value
spotify_shuffle_set:
  alias: Spotify Set Shuffle
  sequence:
  - condition: template
    value_template: >
      {% if is_state_attr("media_player.spotify", "shuffle", false) %} true
      {% else %} false {% endif %}
  - service: media_player.shuffle_set
    data:
      entity_id: media_player.spotify
      shuffle: true
      
# Set the Spotify source
spotify_select_source:
  alias: Spotify Select Source
  sequence:
  - condition: template
    value_template: >
      {% if is_state_attr("media_player.spotify", "source", "Kitchen") %} false
      {% elif is_state_attr("media_player.spotify", "source", "Kitchen Group") %} false
      {% else %} true {% endif %}
  - service: media_player.select_source
    data:
      entity_id: media_player.spotify
      source: Kitchen

# Safe Play Everywhere
play_everywhere:
  alias: 'Play Everywhere Safe'
  sequence:
  - condition: template
    value_template: >
      {% if is_state("media_player.theater", "off") %} true
      {% elif is_state("media_player.theater", "paused") %} true
      {% else %} false {% endif %}
  - service: soundtouch.play_everywhere
    data:
      master: media_player.kitchen
  - service: media_player.volume_set
    data:
      entity_id: media_player.theater
      volume_level: 0.18

# Safe Play Everywhere
play_everywhere_always:
  alias: 'Pair All to Kitchen'
  sequence:
  - service: soundtouch.play_everywhere
    data:
      master: media_player.kitchen
  - service: media_player.volume_set
    data:
      entity_id: media_player.kitchen
      volume_level: 0.35
  - service: media_player.volume_set
    data:
      entity_id: media_player.theater
      volume_level: 0.18
      
# Play PC
play_everywhere_pc:
  alias: 'Pair All to PC'
  sequence:
  - service: soundtouch.play_everywhere
    data:
      master: media_player.pc
  - service: media_player.volume_set
    data:
      entity_id: media_player.kitchen
      volume_level: 0.35
  - service: media_player.volume_set
    data:
      entity_id: media_player.theater
      volume_level: 0.18
      
# Pair PC to Kitchen
pair_pc_to_kitchen:
  alias: 'Pair PC to Kitchen'
  sequence:
  - service: media_player.soundtouch_create_zone
    data:
      master: media_player.kitchen
      slaves: media_player.pc
  - service: media_player.volume_set
    data:
      entity_id: media_player.kitchen
      volume_level: 0.35

# Set PC Audio to AUX
pc_audio_to_aux:
  alias: "Fix PC Audio"
  sequence:
  - service: rest_command.pc_source_select_aux

# Restart Home Assistant
home_assistant_restart:
  alias: Restart
  sequence:
  - service: homeassistant.restart

#  - service: media_player.volume_set
#    data:
#      entity_id: media_player.theater, media_player.kitchen
#      volume_level: 0.2
#  - service: media_player.select_source
#    data:
#      entity_id: media_player.spotify
#      source: Kitchen

garage_opener:
  alias: "Garage Opener"
  sequence:
  - service: mqtt.publish
    data_template:
      topic: home/garage/set
      payload: ''