  - platform: pi_hole
    monitored_conditions:
    
  - platform: rest
    resource: !secret hue_sensor_presence_anybody
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 60
    name: 'Anyone Home'

  - platform: rest
    resource: !secret hue_sensor_presence_victoria
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 120
    name: 'Wife Home'

  - platform: rest
    resource: !secret hue_sensor_presence_leslie
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 120
    name: 'Me Home'

  - platform: rest
    resource: !secret hue_sensor_motion_upstairs
    value_template: '{{ value_json.state.status }}'
    scan_interval: 5
    name: 'Hallway Motion'

  - platform: rest
    resource: !secret hue_sensor_motion_garage
    value_template: '{{ value_json.state.status }}'
    scan_interval: 120
    name: 'Garage Motion'

  - platform: rest
    resource: !secret hue_sensor_motion_patio
    value_template: '{{ value_json.state.status }}'
    scan_interval: 120
    name: 'Patio Motion'

  - platform: rest
    resource: !secret hue_sensor_temperature
    value_template: '{{ (((value_json.state.temperature | float / 100 * 1.8 + 32) * 100) | int / 100) }}'
    scan_interval: 120
    unit_of_measurement: '°F'
    name: 'Hallway Temp'

  - platform: rest
    resource: !secret hue_sensor_temperature_outside
    value_template: '{{ (((value_json.state.temperature | float / 100 * 1.8 + 32) * 100) | int / 100) }}'
    scan_interval: 120
    unit_of_measurement: '°F'
    name: 'Outside Temp'

  - platform: rest
    resource: !secret flux_controller
    value_template: '{{ value_json.FluxStatus.FluxColorTemperature }}'
    scan_interval: 60
    unit_of_measurement: '°K'
    name: 'Flux'

  - platform: rest
    resource: !secret flux_controller
    value_template: '{{ value_json.On }}'
    scan_interval: 60
    name: 'Flux On'
